  version: '3'
  services:

    #PHP Service
    app:
      build:
        context: ./docker/php-fpm/
      container_name: "${DOCKER_PREFIX}-app"
      restart: unless-stopped
      tty: true
      depends_on:
        - db
      environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
      working_dir: /var/www
      user: "1000:1000"
      volumes:
        - ./app:/var/www
        - ./docker/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
        - ./docker/php-fpm/supervisor-workers.conf:/etc/supervisor/conf.d/supervisor-workers.conf
      networks:
        - app-network
    #PostgersSQL Service
    db:
      image: postgres:9.6-alpine
      container_name: "${DOCKER_PREFIX}-db"
      volumes:
        - ./docker/postgres/postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_DB=${DB_DATABASE}
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}
      ports:
        - "8091:5432"
      networks:
        - app-network
    adminer:
      image: adminer
      restart: always
      container_name: "${DOCKER_PREFIX}-adminer"
      ports:
        - 8090:8080
      networks:
        - app-network
    #Nginx Service
    webserver:
      image: nginx:alpine
      container_name: "${DOCKER_PREFIX}-server"
      restart: unless-stopped
      tty: true
      depends_on:
        - app
      ports:
        - "8086:80"
      volumes:
        - ./app:/var/www
        - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
        - /etc/letsencrypt:/etc/letsencrypt/live/laravel.loc/
      networks:
        - app-network

  #Docker Networks
  networks:
    app-network:
      driver: bridge

